server:
  port: ${PORT:7777}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: ${ACTPORT:0}
spring:
  application:
    name: ${NAME:user-service}
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /users/h2-console
  datasource:
    url: jdbc:mariadb://localhost:3306/BeardTrust
    username: beardtrust_dev
    password: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1KVm9jM1lmejFwawo=
    driver-class-name: org.mariadb.jdbc.Driver
authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer
token:
  secret: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj04WnEzS0NCZWQ1UQo=
  expiration: 864000000
login:
  url:
    path: /login
